## Basic Configuration

baseurl = "https://www.doeyo.com.ar/"
builddrafts = false
canonifyurls = false
languageCode = "es-AR"
theme = "hugo-goa"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Bruno Doeyo"
title = "Bruno Doeyo"

## Hugo Built-in Features
enableRobotsTXT = true

## Site Settings
[params]
author = "Bruno Doeyo"
intro = "PSE"
description = "Gasolero y segunda línea"
authorimage = "headshot.jpg"
dateformat = "2006-01-02"

## Site Meta Settings
[params.meta]
description = "Sitio Familiar"
keywords = "doeyo,bruno,iram,rugby,unlzrygby,temperley,gasolero"

## Social Accounts
[params.social]
github = "br1doeyo"
instagram = "br1doeyo"
linkedin = "bdoeyo"
twitter = "br1doeyo"
email = "bruno@doeyo.com.ar"

## Extras
[params.extra]
copyright = "© 2020. Bruno Doeyo. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"